import img1 from "./img1.jpg";

const DUMMY_DATA = [
  {
    id: "i1",
    creator: "u1",
    img: img1,
    name: "product",
    desc: "Some description",
    lprice: 200,
    hprice: 500,
    ethAddress: "kjckjzdkcj",
    wishlist: [],
  },
  {
    id: "i2",
    creator: "u1",
    img: img1,
    name: "product",
    desc: "Some description",
    lprice: 200,
    hprice: 500,
    ethAddress: "kjckjzdkcj",
    wishlist: [],
  },
  {
    id: "i3",
    creator: "u1",
    img: img1,
    name: "product",
    desc: "Some description",
    lprice: 200,
    hprice: 500,
    ethAddress: "kjckjzdkcj",
    wishlist: [],
  },
  {
    id: "i4",
    creator: "u1",
    img: img1,
    name: "product",
    desc: "Some description",
    lprice: 200,
    hprice: 500,
    ethAddress: "kjckjzdkcj",
    wishlist: [],
  },
  {
    id: "i5",
    creator: "u1",
    img: img1,
    name: "product",
    desc: "Some description",
    lprice: 200,
    hprice: 500,
    ethAddress: "kjckjzdkcj",
    wishlist: [],
  },
  {
    id: "i6",
    creator: "u1",
    img: img1,
    name: "product",
    desc: "Some description",
    lprice: 200,
    hprice: 500,
    ethAddress: "kjckjzdkcj",
    wishlist: [],
  },
  {
    id: "i7",
    creator: "u1",
    img: img1,
    name: "product",
    desc: "Some description",
    lprice: 200,
    hprice: 500,
    ethAddress: "kjckjzdkcj",
    wishlist: [],
  },
];
export default DUMMY_DATA;
